### ISSUE TITLE
DropDownMenu problem in 2022.3.0

### ISSUE THREAD

**Issue by vsimanin** [amaximus/transmission-card#27]
![Screenshot_20220304-213147](https://user-images.githubusercontent.com/9263449/156821508-b405dcb6-37de-49a5-af1f-8e2fab06fdd1.jpg)

Please fix it.

**Comment by Olegz73** [comment]
I have the same issue after update on 2022.3.0.  Waiting for fix

**Comment by amaximus** [comment]
Issue fixed in the recentrly released 0.8.3 version.

Please update the card and get back to me with results.

**Comment by vsimanin** [comment]
> Issue fixed in the recentrly released 0.8.3 version.
> 
> Please update the card and get back to me with results.

a drop-down list appeared, but I see 2 problems: 1. it goes from the bottom, the card has become wider, before the list fit on the side;  2. when the list is opened, it flies up to other cards.  Both problems are shown in the screenshots.  Thanks.

![Screenshot_20220306-212612](https://user-images.githubusercontent.com/9263449/156936918-c8a8214f-aaf3-4021-972c-739bae176967.jpg)
![Screenshot_20220306-212643](https://user-images.githubusercontent.com/9263449/156936926-5393f82f-a4fb-470e-819d-5eb6368020af.jpg)

**Comment by rpitera** [comment]
Just updated to the most recent version, but I'm still having the same issue.  Tried refreshing page, clearing cache and even changing the theme but it's still there.  Did I miss something?

**Comment by vsimanin** [comment]
> a drop-down list appeared, but I see 2 problems: 1. it goes from the bottom, the card has become wider, before the list fit on the side; 2. when the list is opened, it flies up to other cards. Both problems are shown in the screenshots. Thanks.

UPD: Add. It's good work on my PC Desktop! But bad in home assistant mobile app for Android.
![изображение](https://user-images.githubusercontent.com/9263449/157116812-ea89ebce-3837-4a1c-9fca-74efa9145148.png)

**Comment by amaximus** [comment]
Checking on the Android companion app (plain Android 10/Android One) it shows just fine:
![Screenshot_20220308-154633](https://user-images.githubusercontent.com/2511168/157261850-4b7c4777-eebe-4f67-b6ea-c8a08de74be0.png)

**Comment by amaximus** [comment]
As a test try to put the card on test view and see if it works there as expected? There are some custom cards that include other cards might break the rendering of the included cards.

**Comment by vsimanin** [comment]
> В качестве теста попробуйте поставить карту на тестовый просмотр и посмотреть, работает ли она там как положено? Есть некоторые пользовательские карты, которые включают в себя другие карты, которые могут нарушить рендеринг включенных карт.

Really.  The problem goes away if you put the card at the very last in the list.  Anywhere else the list jumps up like in my screenshots.  Is there nothing that can be done?  I do not observe such a problem with other cards on the same screen.

**Comment by amaximus** [comment]
Can you please let me know in what card was the transmission card included (some stack, conditional, etc.)?

**Comment by vsimanin** [comment]
> Can you please let me know in what card was the transmission card included (some stack, conditional, etc.)?

no, no special settings.  The cards just go in the list one after another.
